{
    "type": "bundle",
    "id": "bundle--b23bdd40-c8c2-46c1-8f7c-38c4b24f9b6f",
    "spec_version": "2.0",
    "objects": [
        {
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "type": "relationship",
            "id": "relationship--b2852e21-c31a-482a-85fd-00d0990ee8ea",
            "description": "[Bad Rabbit](https://attack.mitre.org/software/S0606) has used various Windows API calls.(Citation: ESET Bad Rabbit)",
            "target_ref": "attack-pattern--391d824f-0ef1-47a0-b0ee-c59a75e27670",
            "modified": "2021-10-15T21:11:22.399Z",
            "source_ref": "malware--2eaa5319-5e1e-4dd7-bbc4-566fced3964a",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "relationship_type": "uses",
            "created": "2021-02-09T14:35:39.656Z",
            "external_references": [
                {
                    "url": "https://www.welivesecurity.com/2017/10/24/bad-rabbit-not-petya-back/",
                    "description": "M.L\u00e9veille, M-E.. (2017, October 24). Bad Rabbit: Not\u2011Petya is back with improved ransomware. Retrieved January 28, 2021.",
                    "source_name": "ESET Bad Rabbit"
                }
            ]
        }
    ]
}