class Fail(Exception):
    pass


class CommandFail(Exception):
    pass
